# Device name
device_name: Volume Mixer

# Display the master volume
master: true

# Display applications
applications: true

# Convert first letter of display names to uppercase
capitalize_names: true

# Update screen timeout in seconds
update_timeout: 5

# Blacklisted applications that should not be displayed
blacklist:
- ShellExperienceHost.exe

# Overwrite the display name for an application
display_names:
  conhost.exe: CMD

# Prioritize to show certain applications
priority:
- firefox.exe
